### ISSUE TITLE
TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by olalonde** [fredericd/marcjs#16]
Getting this error on a particular marc file:

```
/app/node_modules/marcjs/lib/marcjs.js:489
        field[element[0]]['ind1'] = element[1].substring(0,1);
                                              ^

TypeError: Cannot read property 'substring' of undefined
    at /app/node_modules/marcjs/lib/marcjs.js:489:47
    at Array.forEach (native)
    at toMiJ (/app/node_modules/marcjs/lib/marcjs.js:483:17)
    at record (index.js:13:22)
    at reader.on.record (index.js:86:18)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at ReadStream.<anonymous> (/app/node_modules/marcjs/lib/marcjs.js:113:14)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
```

Here's the MARC file triggering this bug:

[sample.mrc.txt](https://github.com/fredericd/marcjs/files/404849/sample.mrc.1.txt)

The bug occurs at record #138 of this file when calling toMiJ() on it. `console.log(record)` on that records outputs:

``` javascript
{ as: [Function],
  toMiJ: [Function],
  append: [Function],
  get: [Function],
  match: [Function],
  leader: '01557nam a2200325zi 4500',
  fields:
   [ [ '001', '28534141' ],
     [ '005', '20160803013253.0' ],
     [ '008', '160120e20130401xxu||||||||||||||||||||' ],
     [ '017', '  ', 'a', 'TX0008220532 /', 'd', '2016-04-22', '2', 'usco' ],
     [ '020', ' 9', 'a', '01550nam  2200' ],
     [ '027', '25', 'z', 'i 45000010009' ],
     [ '035', '00', '0', '000500170000900800390' ],
     [ '040', '02', '6', '017003700065020' ],
     [ '046', '01', '8', '00102' ],
     [ '242',
       '27',
       '0',
       '01700120035002500137040001900162046000900181242007000190245007000260249012800330257001800458269002' ],
     [ '245',
       '00',
       '4',
       '76279014700497300003100644549003900675589017900714590002500893595004000918710006200958710006401020' ],
     [ '249',
       '17',
       '0',
       '06901084953000901153991006201162\u001e28534142\u001e20160803013255.0\u001e160120e20140101xxu||||||||||||||||||||\u001e  ',
       'a',
       'TX0008220250 /',
       'd',
       '2016-0' ],
     [ '257', '-2', '2', 'usco\u001e 9', 'a', '978' ],
     [ '269', '97', '1', '100565\u001e  ', 'a', 'TX0008' ],
     [ '279',
       '20',
       '2',
       '50\u001e  ',
       'a',
       '(DLC-CO)TX 008220250\u001e  ',
       'a',
       'DLC-CO',
       'c',
       'DLC-CO\u001e  ',
       'k',
       '2013\u001e00',
       'a',
       'Fueling Our Future: Exploring Sustainable Energy Use. Grade' ],
     [ '300', ' 6', '-', '8.\u001e00', 'a', 'Fueling Our Future: ' ],
     [ '549', 'xp', 'l', 'oring Sust' ],
     [ '589',
       'in',
       'a',
       'ble Energy Use. Grades 6-8.\u001e  ',
       'c',
       'Western Washington University - Facing the Future.',
       'u',
       'Address: 516 high street MS 9102, Bellingham, WA, 98225, United States.\u001e  ',
       'a',
       'United States\u001e ' ],
     [ '590' ],
     [ '595', 'st', 'e', 'rn Washington University - ' ],
     [ '710',
       'ac',
       'i',
       'ng the Future,',
       'h',
       'employer for hire;',
       'g',
       'Citizenship: United St' ],
     [ '710',
       'te',
       's',
       '.',
       'e',
       'Authorship: text, photograph(s), artwork.\u001e  ',
       'a',
       'Electronic ' ],
     [ '917',
       'il',
       'e',
       ' (eService)\u001e  ',
       'a',
       'new text, artwork and photographs.\u001e  ',
       'a',
       'Rebecca Be' ],
     [ '953', 'rd', 's', 'all, ' ],
     [ '991',
       'es',
       't',
       'ern Washington University - Facing the Future, 516 high st' ] ] }
```

**Comment by olalonde** [comment]
Fixed in PR: https://github.com/fredericd/marcjs/pull/15/commits/0da0ba74093bdd03a72ad98873f699d85a8c9b44#diff-91f74bba0dff14333317c78000ccf6bfL482

**Comment by fredericd** [comment]
Thanks Oli for your two patches. I've grabbed them! I've also update module NPM package to version 0.1.13. You could check whether a standard installation works properly for you.

**Comment by thedeany** [comment]
I'm having the same issue with the `MarcxmlWriter` I believe. I have a record with field 945, but nothing exists in that field (no `element[1]` essentially) and thus it bombs out on line 449. Would the fix for that be similar to the fix presented by @olalonde?

If I should open a new ticket for this, please let me know.

**Comment by fredericd** [comment]
Could you please open a new ticket, and attach a test plan (sample code) to reproduce the bug? Thks.
