### ISSUE TITLE
bin/marcjs throws error with latest version of async

### ISSUE THREAD

**Issue by SydneyUniLibrary-Jim** [fredericd/marcjs#20]
After updating to async v2.5.0, bin/marcjs throws an Error after it outputs the second record.

```
/Users/jim/Documents/Development/git-hub-repos/marcjs/node_modules/async/dist/async.js:903
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/jim/Documents/Development/git-hub-repos/marcjs/node_modules/async/dist/async.js:903:32
    at /Users/jim/Documents/Development/git-hub-repos/marcjs/node_modules/async/dist/async.js:3858:13
    at TextWriter._write (/Users/jim/Documents/Development/git-hub-repos/marcjs/lib/marcjs.js:300:5)
    at Iso2709Reader.<anonymous> (/Users/jim/Documents/Development/git-hub-repos/marcjs/bin/marcjs:41:49)
    at emitOne (events.js:115:13)
    at Iso2709Reader.emit (events.js:210:7)
    at ReadStream.<anonymous> (/Users/jim/Documents/Development/git-hub-repos/marcjs/lib/marcjs.js:113:14)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
```

PR to follow shortly.

**Comment by fredericd** [comment]
Fixed on version 1.0.5, which require node.js v6 and above.
